name: cbofs
on:
  workflow_dispatch:
  schedule:
    - cron: '15 12 * * *'  # run workflow at 12:15 daily

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4      
                
      - name: Set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: cbofs
          environment-file: environment.yml
          channels: conda-forge
          mamba-version: "*"
          channel-priority: strict
          auto-update-conda: false
          auto-activate-base: false          

      - name: Check environment
        run: |
          conda info
          conda list

      - name: Pull data
        run: |-
          current_date=`date +%Y%m%d`
          python scripts/00_get_cbofs.py --tod $current_date

      - name: Commit and push data if changed
        run: |-
          git diff
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Updated data" || exit 0
          git push
          